USE revature_training_db;
DROP TABLE User_Registration;
TRUNCATE TABLE User_Registration;
CREATE TABLE User_Registration( 
	User_id INT UNIQUE PRIMARY KEY AUTO_INCREMENT ,
	NAME VARCHAR(100) NOT NULL,
	Phone VARCHAR(100) UNIQUE NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL,
	CHECK (LENGTH(Phone)=10),
	CHECK(LENGTH(PASSWORD)>=8 AND LENGTH(PASSWORD)<=16),
	ROLE VARCHAR(10) DEFAULT('User') 
);
SELECT * FROM User_Registration; 
INSERT INTO User_Registration(NAME,Phone,Email,PASSWORD,ROLE) VALUES ('Gopi','8220548596','gopi37@gmail.com','gopi3737','Admin');
